# Generated by Django 6.0.5 on 2026-05-15 06:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('user', 'User'), ('group', 'Group')], max_length=10)),
                ('input_name', models.CharField(max_length=255)),
                ('scan_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_repos', models.IntegerField()),
                ('high_risk_count', models.IntegerField(default=0)),
                ('medium_risk_count', models.IntegerField(default=0)),
                ('low_risk_count', models.IntegerField(default=0)),
                ('results_json', models.JSONField()),
            ],
            options={
                'ordering': ['-scan_time'],
            },
        ),
        migrations.CreateModel(
            name='RepositoryScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=255)),
                ('repo_url', models.URLField()),
                ('issues_found', models.JSONField()),
                ('scan_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='scanner_app.scanhistory')),
            ],
        ),
    ]
